// Valeurs éligibles PEA, tous domaines. Garde ce fichier synchronisé
// avec server/watchlist.js (version Node du même projet).

export interface Stock {
  symbol: string;
  name: string;
  sector: string;
}

// Libellés FR utilisés dans les notifications push (cote front, app.js a sa
// propre copie pour l'affichage - garder les deux synchronisees).
export const SECTOR_LABELS: Record<string, string> = {
  sante: "Sante/biotech",
  energie: "Energie",
  finance: "Finance/banque",
  technologie: "Technologie",
  consommation: "Consommation/distribution",
  industrie: "Industrie",
  telecom: "Telecom",
  immobilier: "Immobilier",
  automobile: "Automobile",
};

export const WATCHLIST: Stock[] = [
  { symbol: "IVA.PA", name: "Inventiva", sector: "sante" },
  { symbol: "ALBPS.PA", name: "Biophytis", sector: "sante" },
  { symbol: "VLA.PA", name: "Valneva", sector: "sante" },
  { symbol: "MEDCL.PA", name: "MedinCell", sector: "sante" },
  { symbol: "GNFT.PA", name: "Genfit", sector: "sante" },
  { symbol: "ALCOX.PA", name: "Nicox", sector: "sante" },
  { symbol: "DBV.PA", name: "DBV Technologies", sector: "sante" },
  { symbol: "ABVX.PA", name: "Abivax", sector: "sante" },
  { symbol: "POXEL.PA", name: "Poxel", sector: "sante" },
  { symbol: "ALGEN.PA", name: "Genoway", sector: "sante" },
  { symbol: "ALTHX.PA", name: "THX Pharma (ex-Theranexus)", sector: "sante" },
  { symbol: "OSE.PA", name: "OSE Immunotherapeutics", sector: "sante" },
  { symbol: "ALCLS.PA", name: "Cellectis", sector: "sante" },
  { symbol: "ALNOV.PA", name: "Novacyt", sector: "sante" },

  // Elargissement (France + reste UE/EEE, verifie individuellement via
  // l'API Yahoo Finance avant ajout - eligibilite PEA = siege social UE/EEE).
  { symbol: "SAN.PA", name: "Sanofi", sector: "sante" },
  { symbol: "EL.PA", name: "EssilorLuxottica", sector: "sante" },
  { symbol: "BIM.PA", name: "bioMerieux", sector: "sante" },
  { symbol: "IPN.PA", name: "Ipsen", sector: "sante" },
  { symbol: "VIRP.PA", name: "Virbac", sector: "sante" },
  { symbol: "GBT.PA", name: "Guerbet", sector: "sante" },
  { symbol: "ERF.PA", name: "Eurofins Scientific", sector: "sante" },
  { symbol: "VETO.PA", name: "Vetoquinol", sector: "sante" },
  { symbol: "ADOC.PA", name: "Adocia", sector: "sante" },
  { symbol: "IPH.PA", name: "Innate Pharma", sector: "sante" },
  { symbol: "ABNX.PA", name: "Abionyx Pharma (ex-Cerenis Therapeutics)", sector: "sante" },
  { symbol: "ALDMS.PA", name: "Diagnostic Medical Systems", sector: "sante" },
  { symbol: "ALIMP.PA", name: "Implanet", sector: "sante" },
  { symbol: "ALPRE.PA", name: "Predilife", sector: "sante" },
  { symbol: "ALVAL.PA", name: "Valbiotis", sector: "sante" },
  { symbol: "ALMDT.PA", name: "Median Technologies", sector: "sante" },
  { symbol: "ALBIO.PA", name: "Biosynex", sector: "sante" },
  { symbol: "DIM.PA", name: "Sartorius Stedim Biotech", sector: "sante" },
  { symbol: "EVT.DE", name: "Evotec", sector: "sante" },
  { symbol: "MRK.DE", name: "Merck KGaA", sector: "sante" },
  { symbol: "BAYN.DE", name: "Bayer", sector: "sante" },
  { symbol: "FRE.DE", name: "Fresenius", sector: "sante" },
  { symbol: "FME.DE", name: "Fresenius Medical Care", sector: "sante" },
  { symbol: "SHL.DE", name: "Siemens Healthineers", sector: "sante" },
  { symbol: "SRT3.DE", name: "Sartorius AG", sector: "sante" },
  { symbol: "QIA.DE", name: "Qiagen N.V.", sector: "sante" },
  { symbol: "NOVO-B.CO", name: "Novo Nordisk", sector: "sante" },
  { symbol: "GMAB.CO", name: "Genmab", sector: "sante" },
  { symbol: "AMBU-B.CO", name: "Ambu", sector: "sante" },
  { symbol: "COLO-B.CO", name: "Coloplast", sector: "sante" },
  { symbol: "HLUN-B.CO", name: "H. Lundbeck", sector: "sante" },
  { symbol: "BAVA.CO", name: "Bavarian Nordic", sector: "sante" },
  { symbol: "ZEAL.CO", name: "Zealand Pharma", sector: "sante" },

  { symbol: "TTE.PA", name: "TotalEnergies", sector: "energie" },
  { symbol: "ENGI.PA", name: "Engie", sector: "energie" },
  { symbol: "RUI.PA", name: "Rubis", sector: "energie" },
  { symbol: "VK.PA", name: "Vallourec", sector: "energie" },
  { symbol: "VLTSA.PA", name: "Voltalia", sector: "energie" },
  { symbol: "HDF.PA", name: "Hydrogene de France (HDF Energy)", sector: "energie" },
  { symbol: "LHYFE.PA", name: "Lhyfe", sector: "energie" },
  { symbol: "GTT.PA", name: "Gaztransport & Technigaz (GTT)", sector: "energie" },
  { symbol: "SU.PA", name: "Schneider Electric", sector: "energie" },

  // Elargissement energie (France + reste UE/EEE, meme verification).
  { symbol: "TE.PA", name: "Technip Energies", sector: "energie" },
  { symbol: "NEX.PA", name: "Nexans", sector: "energie" },
  { symbol: "WAGA.PA", name: "Waga Energy", sector: "energie" },
  { symbol: "RWE.DE", name: "RWE", sector: "energie" },
  { symbol: "EOAN.DE", name: "E.ON", sector: "energie" },
  { symbol: "EBK.DE", name: "EnBW Energie Baden-Wurttemberg", sector: "energie" },
  { symbol: "ENR.DE", name: "Siemens Energy", sector: "energie" },
  { symbol: "NDX1.DE", name: "Nordex", sector: "energie" },
  { symbol: "S92.DE", name: "SMA Solar Technology", sector: "energie" },
  { symbol: "PNE3.DE", name: "PNE AG", sector: "energie" },
  { symbol: "F3C.DE", name: "SFC Energy", sector: "energie" },
  { symbol: "IBE.MC", name: "Iberdrola", sector: "energie" },
  { symbol: "REP.MC", name: "Repsol", sector: "energie" },
  { symbol: "NTGY.MC", name: "Naturgy Energy Group", sector: "energie" },
  { symbol: "ANE.MC", name: "Acciona Energias Renovables", sector: "energie" },
  { symbol: "GRE.MC", name: "Grenergy Renovables", sector: "energie" },
  { symbol: "SLR.MC", name: "Solaria Energia y Medio Ambiente", sector: "energie" },
  { symbol: "ENEL.MI", name: "Enel", sector: "energie" },
  { symbol: "ENI.MI", name: "Eni", sector: "energie" },
  { symbol: "A2A.MI", name: "A2A", sector: "energie" },
  { symbol: "TRN.MI", name: "Terna", sector: "energie" },
  { symbol: "SRG.MI", name: "Snam", sector: "energie" },
  { symbol: "ERG.MI", name: "ERG", sector: "energie" },
  { symbol: "EDP.LS", name: "EDP", sector: "energie" },
  { symbol: "EDPR.LS", name: "EDP Renewables", sector: "energie" },
  { symbol: "VER.VI", name: "Verbund", sector: "energie" },
  { symbol: "OMV.VI", name: "OMV", sector: "energie" },
  { symbol: "EVN.VI", name: "EVN", sector: "energie" },
  { symbol: "ELI.BR", name: "Elia Group", sector: "energie" },
  { symbol: "VWS.CO", name: "Vestas Wind Systems", sector: "energie" },
  { symbol: "ORSTED.CO", name: "Orsted", sector: "energie" },
  { symbol: "NESTE.HE", name: "Neste", sector: "energie" },
  { symbol: "FORTUM.HE", name: "Fortum", sector: "energie" },

  // Elargissement multi-domaines (France + reste UE/EEE, meme verification
  // individuelle via l'API Yahoo Finance). EL.PA (EssilorLuxottica, deja en
  // sante), GTT.PA et NEX.PA (deja en energie) ecartes ici pour eviter les
  // doublons de symbole dans la watchlist.
  { symbol: "ABN.AS", name: "ABN AMRO Bank", sector: "finance" },
  { symbol: "AGN.AS", name: "Aegon", sector: "finance" },
  { symbol: "AGS.BR", name: "Ageas", sector: "finance" },
  { symbol: "ALV.DE", name: "Allianz", sector: "finance" },
  { symbol: "AMUN.PA", name: "Amundi", sector: "finance" },
  { symbol: "G.MI", name: "Assicurazioni Generali", sector: "finance" },
  { symbol: "CS.PA", name: "AXA", sector: "finance" },
  { symbol: "SAB.MC", name: "Banco Sabadell", sector: "finance" },
  { symbol: "SAN.MC", name: "Banco Santander", sector: "finance" },
  { symbol: "BBVA.MC", name: "BBVA", sector: "finance" },
  { symbol: "BNP.PA", name: "BNP Paribas", sector: "finance" },
  { symbol: "CABK.MC", name: "CaixaBank", sector: "finance" },
  { symbol: "ACA.PA", name: "Credit Agricole", sector: "finance" },
  { symbol: "DANSKE.CO", name: "Danske Bank", sector: "finance" },
  { symbol: "DB1.DE", name: "Deutsche Borse", sector: "finance" },
  { symbol: "DBK.DE", name: "Deutsche Bank", sector: "finance" },
  { symbol: "ENX.PA", name: "Euronext", sector: "finance" },
  { symbol: "EBS.VI", name: "Erste Group Bank", sector: "finance" },
  { symbol: "HNR1.DE", name: "Hannover Ruck", sector: "finance" },
  { symbol: "INGA.AS", name: "ING Group", sector: "finance" },
  { symbol: "ISP.MI", name: "Intesa Sanpaolo", sector: "finance" },
  { symbol: "KBC.BR", name: "KBC Group", sector: "finance" },
  { symbol: "MB.MI", name: "Mediobanca", sector: "finance" },
  { symbol: "MUV2.DE", name: "Munich Re", sector: "finance" },
  { symbol: "NN.AS", name: "NN Group", sector: "finance" },
  { symbol: "NDA-FI.HE", name: "Nordea Bank", sector: "finance" },
  { symbol: "RBI.VI", name: "Raiffeisen Bank International", sector: "finance" },
  { symbol: "SAMPO.HE", name: "Sampo Oyj", sector: "finance" },
  { symbol: "GLE.PA", name: "Societe Generale", sector: "finance" },
  { symbol: "TLX.DE", name: "Talanx", sector: "finance" },
  { symbol: "UCG.MI", name: "UniCredit", sector: "finance" },
  { symbol: "UNI.MI", name: "Unipol", sector: "finance" },

  { symbol: "ADYEN.AS", name: "Adyen", sector: "technologie" },
  { symbol: "AIXA.DE", name: "AIXTRON", sector: "technologie" },
  { symbol: "ATE.PA", name: "Alten", sector: "technologie" },
  { symbol: "AMS.MC", name: "Amadeus IT Group", sector: "technologie" },
  { symbol: "ASML.AS", name: "ASML Holding", sector: "technologie" },
  { symbol: "ATO.PA", name: "Atos Group", sector: "technologie" },
  { symbol: "BC8.DE", name: "Bechtle", sector: "technologie" },
  { symbol: "BESI.AS", name: "BE Semiconductor Industries (Besi)", sector: "technologie" },
  { symbol: "CAP.PA", name: "Capgemini", sector: "technologie" },
  { symbol: "DSY.PA", name: "Dassault Systemes", sector: "technologie" },
  { symbol: "GFT.DE", name: "GFT Technologies", sector: "technologie" },
  { symbol: "IFX.DE", name: "Infineon Technologies", sector: "technologie" },
  { symbol: "KTN.DE", name: "Kontron", sector: "technologie" },
  { symbol: "NEM.DE", name: "Nemetschek", sector: "technologie" },
  { symbol: "OVH.PA", name: "OVHcloud", sector: "technologie" },
  { symbol: "PRX.AS", name: "Prosus", sector: "technologie" },
  { symbol: "SAP.DE", name: "SAP", sector: "technologie" },
  { symbol: "SESG.PA", name: "SES", sector: "technologie" },
  { symbol: "SOI.PA", name: "Soitec", sector: "technologie" },
  { symbol: "SW.PA", name: "Sopra Steria", sector: "technologie" },
  { symbol: "STMPA.PA", name: "STMicroelectronics", sector: "technologie" },
  { symbol: "TMV.DE", name: "TeamViewer", sector: "technologie" },
  { symbol: "TEP.PA", name: "Teleperformance", sector: "technologie" },
  { symbol: "UTDI.DE", name: "United Internet", sector: "technologie" },
  { symbol: "WKL.AS", name: "Wolters Kluwer", sector: "technologie" },
  { symbol: "WLN.PA", name: "Worldline", sector: "technologie" },

  { symbol: "ABI.BR", name: "AB InBev", sector: "consommation" },
  { symbol: "ADS.DE", name: "Adidas", sector: "consommation" },
  { symbol: "BEI.DE", name: "Beiersdorf", sector: "consommation" },
  { symbol: "BON.PA", name: "Bonduelle", sector: "consommation" },
  { symbol: "CARL-B.CO", name: "Carlsberg", sector: "consommation" },
  { symbol: "CA.PA", name: "Carrefour", sector: "consommation" },
  { symbol: "CDI.PA", name: "Christian Dior", sector: "consommation" },
  { symbol: "BN.PA", name: "Danone", sector: "consommation" },
  { symbol: "FDJU.PA", name: "FDJ United", sector: "consommation" },
  { symbol: "SK.PA", name: "Groupe SEB", sector: "consommation" },
  { symbol: "HEIA.AS", name: "Heineken", sector: "consommation" },
  { symbol: "HEN3.DE", name: "Henkel", sector: "consommation" },
  { symbol: "RMS.PA", name: "Hermes International", sector: "consommation" },
  { symbol: "ITX.MC", name: "Inditex", sector: "consommation" },
  { symbol: "JMT.LS", name: "Jeronimo Martins", sector: "consommation" },
  { symbol: "KER.PA", name: "Kering", sector: "consommation" },
  { symbol: "OR.PA", name: "L'Oreal", sector: "consommation" },
  { symbol: "MC.PA", name: "LVMH", sector: "consommation" },
  { symbol: "RI.PA", name: "Pernod Ricard", sector: "consommation" },
  { symbol: "PUM.DE", name: "Puma", sector: "consommation" },
  { symbol: "RCO.PA", name: "Remy Cointreau", sector: "consommation" },

  { symbol: "AI.PA", name: "Air Liquide", sector: "industrie" },
  { symbol: "AIR.PA", name: "Airbus", sector: "industrie" },
  { symbol: "AKZA.AS", name: "AkzoNobel", sector: "industrie" },
  { symbol: "ALO.PA", name: "Alstom", sector: "industrie" },
  { symbol: "MT.AS", name: "ArcelorMittal", sector: "industrie" },
  { symbol: "EN.PA", name: "Bouygues", sector: "industrie" },
  { symbol: "DSFIR.AS", name: "DSM-Firmenich", sector: "industrie" },
  { symbol: "FGR.PA", name: "Eiffage", sector: "industrie" },
  { symbol: "HEI.DE", name: "HeidelbergMaterials", sector: "industrie" },
  { symbol: "IMCD.AS", name: "IMCD", sector: "industrie" },
  { symbol: "KNEBV.HE", name: "Kone", sector: "industrie" },
  { symbol: "LR.PA", name: "Legrand", sector: "industrie" },
  { symbol: "MTX.DE", name: "MTU Aero Engines", sector: "industrie" },
  { symbol: "PRY.MI", name: "Prysmian", sector: "industrie" },
  { symbol: "RXL.PA", name: "Rexel", sector: "industrie" },
  { symbol: "SAF.PA", name: "Safran", sector: "industrie" },
  { symbol: "SGO.PA", name: "Saint-Gobain", sector: "industrie" },
  { symbol: "SIE.DE", name: "Siemens", sector: "industrie" },
  { symbol: "HO.PA", name: "Thales", sector: "industrie" },
  { symbol: "TKA.DE", name: "ThyssenKrupp", sector: "industrie" },
  { symbol: "VIE.PA", name: "Veolia Environnement", sector: "industrie" },
  { symbol: "DG.PA", name: "Vinci", sector: "industrie" },

  { symbol: "CLNX.MC", name: "Cellnex Telecom", sector: "telecom" },
  { symbol: "DTE.DE", name: "Deutsche Telekom", sector: "telecom" },
  { symbol: "ELISA.HE", name: "Elisa", sector: "telecom" },
  { symbol: "ERIC-B.ST", name: "Ericsson", sector: "telecom" },
  { symbol: "FNTN.DE", name: "freenet", sector: "telecom" },
  { symbol: "1U1.DE", name: "1&1 AG", sector: "telecom" },
  { symbol: "KPN.AS", name: "KPN", sector: "telecom" },
  { symbol: "NOKIA.HE", name: "Nokia", sector: "telecom" },
  { symbol: "NOS.LS", name: "NOS SGPS", sector: "telecom" },
  { symbol: "ORA.PA", name: "Orange", sector: "telecom" },
  { symbol: "HTO.AT", name: "OTE (Hellenic Telecommunications)", sector: "telecom" },
  { symbol: "PROX.BR", name: "Proximus", sector: "telecom" },
  { symbol: "TEL2-B.ST", name: "Tele2", sector: "telecom" },
  { symbol: "TIT.MI", name: "Telecom Italia", sector: "telecom" },
  { symbol: "TEF.MC", name: "Telefonica", sector: "telecom" },

  { symbol: "AED.BR", name: "Aedifica", sector: "immobilier" },
  { symbol: "ALTA.PA", name: "Altarea", sector: "immobilier" },
  { symbol: "ARG.PA", name: "Argan", sector: "immobilier" },
  { symbol: "AT1.DE", name: "Aroundtown", sector: "immobilier" },
  { symbol: "COL.MC", name: "Colonial (Inmobiliaria Colonial)", sector: "immobilier" },
  { symbol: "COV.PA", name: "Covivio", sector: "immobilier" },
  { symbol: "DWNI.DE", name: "Deutsche Wohnen", sector: "immobilier" },
  { symbol: "GFC.PA", name: "Gecina", sector: "immobilier" },
  { symbol: "GYC.DE", name: "Grand City Properties", sector: "immobilier" },
  { symbol: "ICAD.PA", name: "Icade", sector: "immobilier" },
  { symbol: "LI.PA", name: "Klepierre", sector: "immobilier" },
  { symbol: "LEG.DE", name: "LEG Immobilien", sector: "immobilier" },
  { symbol: "MERY.PA", name: "Mercialys", sector: "immobilier" },
  { symbol: "MRL.MC", name: "Merlin Properties", sector: "immobilier" },
  { symbol: "TEG.DE", name: "TAG Immobilien", sector: "immobilier" },
  { symbol: "URW.PA", name: "Unibail-Rodamco-Westfield", sector: "immobilier" },
  { symbol: "VNA.DE", name: "Vonovia", sector: "immobilier" },
  { symbol: "WDP.BR", name: "Warehouses De Pauw (WDP)", sector: "immobilier" },
  { symbol: "WHA.AS", name: "Wereldhave", sector: "immobilier" },

  { symbol: "BMW.DE", name: "BMW", sector: "automobile" },
  { symbol: "CON.DE", name: "Continental", sector: "automobile" },
  { symbol: "FRVIA.PA", name: "Forvia", sector: "automobile" },
  { symbol: "IVG.MI", name: "Iveco Group", sector: "automobile" },
  { symbol: "MBG.DE", name: "Mercedes-Benz Group", sector: "automobile" },
  { symbol: "ML.PA", name: "Michelin", sector: "automobile" },
  { symbol: "NOEJ.DE", name: "Norma Group", sector: "automobile" },
  { symbol: "OPM.PA", name: "OPmobility (ex-Plastic Omnium)", sector: "automobile" },
  { symbol: "P911.DE", name: "Porsche AG", sector: "automobile" },
  { symbol: "RNO.PA", name: "Renault", sector: "automobile" },
  { symbol: "STLAP.PA", name: "Stellantis", sector: "automobile" },
  { symbol: "8TRA.DE", name: "Traton", sector: "automobile" },
  { symbol: "FR.PA", name: "Valeo", sector: "automobile" },
  { symbol: "VOW3.DE", name: "Volkswagen", sector: "automobile" },
  { symbol: "VOLCAR-B.ST", name: "Volvo Cars", sector: "automobile" },
];
