// Valeurs santé/biotech et énergie éligibles PEA. Garde ce fichier synchronisé
// avec server/watchlist.js (version Node du même projet).

export interface Stock {
  symbol: string;
  name: string;
  sector: "sante" | "energie";
}

export const WATCHLIST: Stock[] = [
  { symbol: "IVA.PA", name: "Inventiva", sector: "sante" },
  { symbol: "ALBPS.PA", name: "Biophytis", sector: "sante" },
  { symbol: "VLA.PA", name: "Valneva", sector: "sante" },
  { symbol: "MEDCL.PA", name: "MedinCell", sector: "sante" },
  { symbol: "GNFT.PA", name: "Genfit", sector: "sante" },
  { symbol: "ALCOX.PA", name: "Nicox", sector: "sante" },
  { symbol: "DBV.PA", name: "DBV Technologies", sector: "sante" },
  { symbol: "ABVX.PA", name: "Abivax", sector: "sante" },
  { symbol: "POXEL.PA", name: "Poxel", sector: "sante" },
  { symbol: "ALGEN.PA", name: "Genoway", sector: "sante" },
  { symbol: "ALTHX.PA", name: "THX Pharma (ex-Theranexus)", sector: "sante" },
  { symbol: "OSE.PA", name: "OSE Immunotherapeutics", sector: "sante" },
  { symbol: "ALCLS.PA", name: "Cellectis", sector: "sante" },
  { symbol: "ALNOV.PA", name: "Novacyt", sector: "sante" },

  // Elargissement (France + reste UE/EEE, verifie individuellement via
  // l'API Yahoo Finance avant ajout - eligibilite PEA = siege social UE/EEE).
  { symbol: "SAN.PA", name: "Sanofi", sector: "sante" },
  { symbol: "EL.PA", name: "EssilorLuxottica", sector: "sante" },
  { symbol: "BIM.PA", name: "bioMerieux", sector: "sante" },
  { symbol: "IPN.PA", name: "Ipsen", sector: "sante" },
  { symbol: "VIRP.PA", name: "Virbac", sector: "sante" },
  { symbol: "GBT.PA", name: "Guerbet", sector: "sante" },
  { symbol: "ERF.PA", name: "Eurofins Scientific", sector: "sante" },
  { symbol: "VETO.PA", name: "Vetoquinol", sector: "sante" },
  { symbol: "ADOC.PA", name: "Adocia", sector: "sante" },
  { symbol: "IPH.PA", name: "Innate Pharma", sector: "sante" },
  { symbol: "ABNX.PA", name: "Abionyx Pharma (ex-Cerenis Therapeutics)", sector: "sante" },
  { symbol: "ALDMS.PA", name: "Diagnostic Medical Systems", sector: "sante" },
  { symbol: "ALIMP.PA", name: "Implanet", sector: "sante" },
  { symbol: "ALPRE.PA", name: "Predilife", sector: "sante" },
  { symbol: "ALVAL.PA", name: "Valbiotis", sector: "sante" },
  { symbol: "ALMDT.PA", name: "Median Technologies", sector: "sante" },
  { symbol: "ALBIO.PA", name: "Biosynex", sector: "sante" },
  { symbol: "DIM.PA", name: "Sartorius Stedim Biotech", sector: "sante" },
  { symbol: "EVT.DE", name: "Evotec", sector: "sante" },
  { symbol: "MRK.DE", name: "Merck KGaA", sector: "sante" },
  { symbol: "BAYN.DE", name: "Bayer", sector: "sante" },
  { symbol: "FRE.DE", name: "Fresenius", sector: "sante" },
  { symbol: "FME.DE", name: "Fresenius Medical Care", sector: "sante" },
  { symbol: "SHL.DE", name: "Siemens Healthineers", sector: "sante" },
  { symbol: "SRT3.DE", name: "Sartorius AG", sector: "sante" },
  { symbol: "QIA.DE", name: "Qiagen N.V.", sector: "sante" },
  { symbol: "NOVO-B.CO", name: "Novo Nordisk", sector: "sante" },
  { symbol: "GMAB.CO", name: "Genmab", sector: "sante" },
  { symbol: "AMBU-B.CO", name: "Ambu", sector: "sante" },
  { symbol: "COLO-B.CO", name: "Coloplast", sector: "sante" },
  { symbol: "HLUN-B.CO", name: "H. Lundbeck", sector: "sante" },
  { symbol: "BAVA.CO", name: "Bavarian Nordic", sector: "sante" },
  { symbol: "ZEAL.CO", name: "Zealand Pharma", sector: "sante" },

  { symbol: "TTE.PA", name: "TotalEnergies", sector: "energie" },
  { symbol: "ENGI.PA", name: "Engie", sector: "energie" },
  { symbol: "RUI.PA", name: "Rubis", sector: "energie" },
  { symbol: "VK.PA", name: "Vallourec", sector: "energie" },
  { symbol: "VLTSA.PA", name: "Voltalia", sector: "energie" },
  { symbol: "HDF.PA", name: "Hydrogene de France (HDF Energy)", sector: "energie" },
  { symbol: "LHYFE.PA", name: "Lhyfe", sector: "energie" },
  { symbol: "GTT.PA", name: "Gaztransport & Technigaz (GTT)", sector: "energie" },
  { symbol: "SU.PA", name: "Schneider Electric", sector: "energie" },

  // Elargissement energie (France + reste UE/EEE, meme verification).
  { symbol: "TE.PA", name: "Technip Energies", sector: "energie" },
  { symbol: "NEX.PA", name: "Nexans", sector: "energie" },
  { symbol: "WAGA.PA", name: "Waga Energy", sector: "energie" },
  { symbol: "RWE.DE", name: "RWE", sector: "energie" },
  { symbol: "EOAN.DE", name: "E.ON", sector: "energie" },
  { symbol: "EBK.DE", name: "EnBW Energie Baden-Wurttemberg", sector: "energie" },
  { symbol: "ENR.DE", name: "Siemens Energy", sector: "energie" },
  { symbol: "NDX1.DE", name: "Nordex", sector: "energie" },
  { symbol: "S92.DE", name: "SMA Solar Technology", sector: "energie" },
  { symbol: "PNE3.DE", name: "PNE AG", sector: "energie" },
  { symbol: "F3C.DE", name: "SFC Energy", sector: "energie" },
  { symbol: "IBE.MC", name: "Iberdrola", sector: "energie" },
  { symbol: "REP.MC", name: "Repsol", sector: "energie" },
  { symbol: "NTGY.MC", name: "Naturgy Energy Group", sector: "energie" },
  { symbol: "ANE.MC", name: "Acciona Energias Renovables", sector: "energie" },
  { symbol: "GRE.MC", name: "Grenergy Renovables", sector: "energie" },
  { symbol: "SLR.MC", name: "Solaria Energia y Medio Ambiente", sector: "energie" },
  { symbol: "ENEL.MI", name: "Enel", sector: "energie" },
  { symbol: "ENI.MI", name: "Eni", sector: "energie" },
  { symbol: "A2A.MI", name: "A2A", sector: "energie" },
  { symbol: "TRN.MI", name: "Terna", sector: "energie" },
  { symbol: "SRG.MI", name: "Snam", sector: "energie" },
  { symbol: "ERG.MI", name: "ERG", sector: "energie" },
  { symbol: "EDP.LS", name: "EDP", sector: "energie" },
  { symbol: "EDPR.LS", name: "EDP Renewables", sector: "energie" },
  { symbol: "VER.VI", name: "Verbund", sector: "energie" },
  { symbol: "OMV.VI", name: "OMV", sector: "energie" },
  { symbol: "EVN.VI", name: "EVN", sector: "energie" },
  { symbol: "ELI.BR", name: "Elia Group", sector: "energie" },
  { symbol: "VWS.CO", name: "Vestas Wind Systems", sector: "energie" },
  { symbol: "ORSTED.CO", name: "Orsted", sector: "energie" },
  { symbol: "NESTE.HE", name: "Neste", sector: "energie" },
  { symbol: "FORTUM.HE", name: "Fortum", sector: "energie" },
];
